/* ============================================================
   OVERTONE — THE VIDEO GAME CODEX
   Each entry ties a real track to a theory device you can hear
   and then play yourself in the Lab.

   Facts (composer, game, year, hardware) are documented.
   Analysis (mode, device) is the common reading among analysts —
   music this rich rarely has exactly one correct answer, so the
   copy says "built on" and "reads as" rather than pretending
   there is a single right label.

   link: {scale:'id'} or {prog:'id'} — wires the codex to the Lab
   ============================================================ */
window.OT = window.OT || {};

OT.ERAS = [
  ['all','Everything'],
  ['8bit','8-bit · NES & Game Boy'],
  ['16bit','16-bit · SNES & Genesis'],
  ['cd','CD era · PS1 & N64'],
  ['modern','Modern']
];

OT.VGM = [
  /* ================= 8-BIT ================= */
  {id:'smb-overworld', t:'Overworld Theme', g:'Super Mario Bros.', c:'Koji Kondo', y:1985, sys:'NES', era:'8bit',
   dev:'Major scale · I–IV–V', link:{scale:'ionian'},
   why:'Kondo had three melodic channels and wrote one of the most recognisable tunes ever made inside that limit. The harmony is almost entirely the three primary major triads, which is why it reads as pure optimism with no ambiguity anywhere.',
   listen:'The bass line is doing enormous work — it walks and swings underneath while the melody stays syncopated above it. Two voices doing completely different jobs.'},
  {id:'smb-underground', t:'Underground Theme', g:'Super Mario Bros.', c:'Koji Kondo', y:1985, sys:'NES', era:'8bit',
   dev:'Pentatonic · octave displacement', link:{scale:'majpent'},
   why:'Almost no harmony at all — mostly a single line doubled at the octave with heavy space around it. The emptiness is the composition.',
   listen:'How much of the effect comes from silence and the descending octave leap. Fewer notes, more room, instantly claustrophobic.'},
  {id:'smb-water', t:'Underwater Theme', g:'Super Mario Bros.', c:'Koji Kondo', y:1985, sys:'NES', era:'8bit',
   dev:'Waltz · 3/4 as weightlessness', link:{rhythm:'waltz'},
   why:'Nothing in the music imitates water. Kondo instead wrote a waltz, and the three-beat lilt makes you feel like you are floating through the level rather than walking.',
   listen:'The lift on beat one. That gentle rotation is the entire trick, and it is a rhythmic idea rather than a melodic one.'},
  {id:'zelda-overworld', t:'Overworld Theme', g:'The Legend of Zelda', c:'Koji Kondo', y:1986, sys:'NES', era:'8bit',
   dev:'Heroic major · relentless triplets', link:{scale:'ionian'},
   why:'Written in a hurry after the original plan to use Ravel\u2019s Bolero fell through when Kondo learned it was still in copyright. The replacement became the most recognisable adventure theme in games.',
   listen:'The melody almost never stops moving. Constant motion reads as travel — you are never standing still while it plays.'},
  {id:'mm2-airman', t:'Air Man Stage', g:'Mega Man 2', c:'Takashi Tateishi', y:1988, sys:'NES', era:'8bit',
   dev:'Dorian · driving eighths', link:{scale:'dorian'},
   why:'Minor tonality with a raised 6th keeps the stage urgent without turning it grim. This is the Mega Man formula in one track: hard, fast, and never actually sad.',
   listen:'The bass is a separate composition, not a root-note pad. Mega Man 2 puts real melodic writing in the low channel.'},
  {id:'mm2-wily', t:'Dr. Wily Stage 1', g:'Mega Man 2', c:'Takashi Tateishi', y:1988, sys:'NES', era:'8bit',
   dev:'Minor pentatonic · shred lead', link:{scale:'minpent'},
   why:'Widely covered by metal guitarists, and for good reason — the lead line is essentially a rock solo written for a square wave. The pentatonic shape survives the channel limit perfectly.',
   listen:'The arpeggiated accompaniment under the lead. One channel is faking an entire rhythm section by moving fast enough.'},
  {id:'castlevania-vampire', t:'Vampire Killer', g:'Castlevania', c:'Kinuyo Yamashita', y:1986, sys:'NES', era:'8bit',
   dev:'Natural minor · descending bass', link:{scale:'aeolian'},
   why:'Minor-key drive with a stepwise falling bass under it. That descent is the same device Baroque composers used for lament, running here at arcade tempo.',
   listen:'The bass walking down while the melody climbs. Contrary motion between the two lines is what gives it the tension.'},
  {id:'castlevania-bloody', t:'Bloody Tears', g:'Castlevania II: Simon\u2019s Quest', c:'Kenichi Matsubara', y:1987, sys:'NES', era:'8bit',
   dev:'Harmonic minor · augmented 2nd', link:{scale:'harmonic'},
   why:'The raised 7th over a minor scale creates the gap between ♭6 and 7 that reads instantly as gothic. The whole Castlevania identity is built on this one interval.',
   listen:'That leap near the top of the phrase. It is the augmented second, and it is doing all the atmospheric work.'},
  {id:'ff-prelude', t:'Prelude', g:'Final Fantasy', c:'Nobuo Uematsu', y:1987, sys:'NES', era:'8bit',
   dev:'Arpeggio · two chords, infinite space', link:{scale:'ionian'},
   why:'Uematsu wrote it in about ten minutes: a rising and falling arpeggio over two alternating chords. Thirty-plus years later it still opens the series.',
   listen:'There is no melody. The arpeggio is the melody — harmony played horizontally instead of vertically.'},
  {id:'pokemon-lavender', t:'Lavender Town', g:'Pokémon Red & Blue', c:'Junichi Masuda', y:1996, sys:'Game Boy', era:'8bit',
   dev:'Harmonic minor · dissonant ostinato', link:{scale:'harmonic'},
   why:'A repeating figure with unresolved intervals stacked over it, on hardware with two pulse channels and a lot of hiss. Genuinely unsettling to a generation of children.',
   listen:'Nothing resolves. The loop returns to where it started without ever answering the question it asked.'},
  {id:'kirby-green', t:'Green Greens', g:'Kirby\u2019s Dream Land', c:'Jun Ishikawa', y:1992, sys:'Game Boy', era:'8bit',
   dev:'Major · I–V–vi–IV feel', link:{prog:'axis'},
   why:'Bright, bouncing and diatonic to a fault. Kirby\u2019s music has always used simple harmony played with enormous rhythmic personality.',
   listen:'The rhythm carries the character, not the chords. Same progression as a thousand pop songs, entirely different energy.'},

  /* ================= 16-BIT ================= */
  {id:'sonic-green-hill', t:'Green Hill Zone', g:'Sonic the Hedgehog', c:'Masato Nakamura', y:1991, sys:'Genesis', era:'16bit',
   dev:'Mixolydian brightness · funk bass', link:{scale:'mixolydian'},
   why:'Written by the bassist of the pop band Dreams Come True, which explains everything about that bass line. The flat 7th keeps it from ever sounding like it wants to stop.',
   listen:'The bass is the hook. On the Genesis FM chip it has a slap-like attack that no other console of the era could produce.'},
  {id:'ct-main-theme', t:'Chrono Trigger (Main Theme)', g:'Chrono Trigger', c:'Yasunori Mitsuda', y:1995, sys:'SNES', era:'16bit',
   dev:'Modal mixture · borrowed ♭6', link:{scale:'harmmaj'},
   why:'Bright and forward-moving with one note of grief folded in. That mixture of major optimism and borrowed minor colour is the entire emotional thesis of the game.',
   listen:'The moment the harmony darkens for a single chord and then recovers. Mitsuda does this constantly and it is why the score aches.'},
  {id:'ct-corridors', t:'Corridors of Time', g:'Chrono Trigger', c:'Yasunori Mitsuda', y:1995, sys:'SNES', era:'16bit',
   dev:'Aeolian · ostinato over a static bass', link:{scale:'aeolian'},
   why:'A hypnotic repeating figure over an almost unchanging bass. Mitsuda reportedly wrote much of this score while ill, and the exhaustion is audible as stillness.',
   listen:'The bass barely moves for long stretches. All the motion is in the upper voices circling above it — which is exactly why it feels like standing outside time.'},
  {id:'ct-brink-of-time', t:'Brink of Time', g:'Chrono Trigger', c:'Yasunori Mitsuda', y:1995, sys:'SNES', era:'16bit',
   dev:'Jazz harmony · walking bass', link:{scale:'melodic'},
   why:'An openly jazz-influenced cue on a cartridge — walking bass, extended chords, swung feel. Remarkable given eight sample channels and 64KB of audio RAM.',
   listen:'Extensions above the basic triads. Ninths and thirteenths on SNES hardware, where every sample had to be paid for in kilobytes.'},
  {id:'ct-secret-forest', t:'Secret of the Forest', g:'Chrono Trigger', c:'Yasunori Mitsuda', y:1995, sys:'SNES', era:'16bit',
   dev:'Suspended harmony · pedal tone', link:{chord:'sus2'},
   why:'Built on chords that refuse to commit to major or minor, sitting over a held bass note. Ambiguity as an atmosphere rather than a problem to solve.',
   listen:'The bass note that stays put while chords change above it. That is a pedal tone, and it makes everything above it sound like weather.'},
  {id:'ff6-terra', t:'Terra\u2019s Theme', g:'Final Fantasy VI', c:'Nobuo Uematsu', y:1994, sys:'SNES', era:'16bit',
   dev:'Mixolydian overworld · ♭VII', link:{scale:'mixolydian'},
   why:'The flat 7th chord is the sound of the world opening up. Losing the leading tone removes the pull home, so the music travels instead of resolving.',
   listen:'The chord that should be the dominant but is a whole step lower instead. That substitution is most of the wanderlust.'},
  {id:'ff6-dancing-mad', t:'Dancing Mad', g:'Final Fantasy VI', c:'Nobuo Uematsu', y:1994, sys:'SNES', era:'16bit',
   dev:'Whole tone & chromatic collapse', link:{scale:'wholetone'},
   why:'A multi-movement final boss piece that moves from pipe organ toccata to rock. As Kefka comes apart, so does the tonal centre — symmetrical scales dissolve the sense of key.',
   listen:'The organ section quoting Bach\u2019s vocabulary, then the harmony losing its footing on purpose as the fight escalates.'},
  {id:'ff6-johnny', t:'Johnny C. Bad', g:'Final Fantasy VI', c:'Nobuo Uematsu', y:1994, sys:'SNES', era:'16bit',
   dev:'Blues scale · shuffle feel', link:{scale:'blues'},
   why:'A straight blues on a Super Nintendo, complete with blue notes and a swung rhythm section. Uematsu treated the SPC700 as a band rather than a chip.',
   listen:'The bend into the flat 5. On sampled hardware that had to be written as a pitch slide by hand.'},
  {id:'ff4-theme', t:'Main Theme (Overworld)', g:'Final Fantasy IV', c:'Nobuo Uematsu', y:1991, sys:'SNES', era:'16bit',
   dev:'Lydian lift · soaring topic', link:{scale:'lydian'},
   why:'Music theorists have described a "soaring topic" in game scoring — rising lines and raised fourths used specifically for flight. Final Fantasy IV is one of the standard examples.',
   listen:'The upward reach in the melody and the brightness of the chord underneath it. Flight written as harmony rather than sound effects.'},
  {id:'zelda-lttp-hyrule', t:'Hyrule Castle', g:'The Legend of Zelda: A Link to the Past', c:'Koji Kondo', y:1991, sys:'SNES', era:'16bit',
   dev:'Minor march · chromatic bass', link:{scale:'aeolian'},
   why:'A processional in minor with chromatic movement in the bass, which is how the same series that scored sunny overworlds signals dread.',
   listen:'The bass creeping by half-steps. Chromatic motion has no home key, so it feels like the ground is unreliable.'},
  {id:'dkc-aquatic', t:'Aquatic Ambience', g:'Donkey Kong Country', c:'David Wise', y:1994, sys:'SNES', era:'16bit',
   dev:'Suspended chords · reverb as instrument', link:{chord:'sus2'},
   why:'Wise pushed the SPC700\u2019s built-in echo hardware as a compositional element rather than a polish layer. The space between notes is the piece.',
   listen:'The delay tails overlapping into chords of their own. That echo is on the sound chip, not added afterwards.'},

  /* ================= CD ERA ================= */
  {id:'zelda-lost-woods', t:'Lost Woods (Saria\u2019s Song)', g:'Ocarina of Time', c:'Koji Kondo', y:1998, sys:'N64', era:'cd',
   dev:'Lydian colour · ♯4', link:{scale:'lydian'},
   why:'The opening figure leans on the raised fourth, which is the standard textbook example of Lydian in game music. The second half settles back toward plain major — Kondo uses the mode as a colour to pass through, not a home.',
   listen:'The tritone against the root in the first few notes. It is unresolved, which is exactly what being lost sounds like.'},
  {id:'zelda-lullaby', t:'Zelda\u2019s Lullaby', g:'Ocarina of Time', c:'Koji Kondo', y:1998, sys:'N64', era:'cd',
   dev:'Lydian · II over I', link:{scale:'lydian'},
   why:'The signature sound comes from a major chord built on the second degree sitting over the tonic in the bass. That combination spells out the raised fourth without ever stating a scale.',
   listen:'The bass note staying still while the chord above it shifts up a whole step and back. Pastoral, slightly mysterious, entirely harmonic.'},
  {id:'zelda-hyrule-field', t:'Hyrule Field', g:'Ocarina of Time', c:'Koji Kondo', y:1998, sys:'N64', era:'cd',
   dev:'Modal mixture · ♭VII–I', link:{scale:'mixolydian'},
   why:'The melody moves between modes that share a lowered seventh, and the harmony leans on the flat-seven chord resolving up to the tonic. Adventure, harmonised.',
   listen:'The seventh degree changing from lowered to raised across the phrase. That flicker is the whole colour.'},
  {id:'zelda-gerudo', t:'Gerudo Valley', g:'Ocarina of Time', c:'Koji Kondo', y:1998, sys:'N64', era:'cd',
   dev:'Phrygian dominant · Spanish idiom', link:{scale:'phrygdom'},
   why:'Flamenco guitar vocabulary translated into a game score: a major third sitting above a flat second, with the augmented-second gap that defines the sound.',
   listen:'The half-step above the root against a bright major chord. That contradiction is the whole flavour.'},
  {id:'ff7-aerith', t:'Aerith\u2019s Theme', g:'Final Fantasy VII', c:'Nobuo Uematsu', y:1997, sys:'PS1', era:'cd',
   dev:'Royal Road · IV–V–iii–vi', link:{prog:'royalroad'},
   why:'Uses the progression pattern that runs through so much Japanese popular music — beginning away from the tonic and landing on the relative minor instead of home.',
   listen:'The cadence that should resolve to the tonic and lands on vi instead. Postponed resolution is why it feels like held grief.'},
  {id:'ff7-battle', t:'Those Who Fight', g:'Final Fantasy VII', c:'Nobuo Uematsu', y:1997, sys:'PS1', era:'cd',
   dev:'Minor pentatonic riff · ♭VI–♭VII–i', link:{scale:'minpent'},
   why:'A rock riff structure in a battle theme. The stepwise climb up to the tonic from below is standard heavy-metal harmonic vocabulary.',
   listen:'The riff is rhythmic first and melodic second — it works because of where the accents land, not which notes they are.'},
  {id:'ff7-jenova', t:'J-E-N-O-V-A', g:'Final Fantasy VII', c:'Nobuo Uematsu', y:1997, sys:'PS1', era:'cd',
   dev:'Dorian drive · chromatic tension', link:{scale:'dorian'},
   why:'Fast minor-mode writing with chromatic decoration over an insistent pulse. The raised sixth keeps it aggressive rather than mournful.',
   listen:'The choir-like pads underneath. The PlayStation could stream real samples, and Uematsu immediately used them for texture rather than melody.'},
  {id:'ff7-one-winged', t:'One-Winged Angel', g:'Final Fantasy VII', c:'Nobuo Uematsu', y:1997, sys:'PS1', era:'cd',
   dev:'Octatonic tension · Latin chant', link:{scale:'octatonic'},
   why:'Uematsu has said he was thinking about Stravinsky and Orff. The result stacks short cells of dissonance rather than developing melodies, which is why it feels mechanical and enormous.',
   listen:'The riff is built from small repeating fragments, not a tune. The chorus arrives late and is treated as a percussion instrument.'},
  {id:'mgs-encounter', t:'Encounter', g:'Metal Gear Solid', c:'Konami sound team', y:1998, sys:'PS1', era:'cd',
   dev:'Diminished tension · dynamic scoring', link:{scale:'octatonic'},
   why:'Alert music that has to loop indefinitely without becoming boring or resolving. Diminished harmony is perfect for that job — it is all tension and no home.',
   listen:'Nothing ever cadences. The music cannot resolve because the game state has not resolved either.'},

  /* ================= MODERN ================= */
  {id:'doom-e1m1', t:'At Doom\u2019s Gate (E1M1)', g:'DOOM', c:'Bobby Prince', y:1993, sys:'PC', era:'modern',
   dev:'Phrygian riff · power chords', link:{scale:'phrygian'},
   why:'Prince was asked to write music in the style of the metal bands the team liked. The flat second over a driving low riff is the sound of that entire genre compressed into a loop.',
   listen:'The riff sits almost entirely on the bottom two notes of the scale. Range is not what makes it heavy — repetition and the half-step are.'},
  {id:'undertale-megalo', t:'MEGALOVANIA', g:'Undertale', c:'Toby Fox', y:2015, sys:'PC', era:'modern',
   dev:'Natural minor · relentless ostinato', link:{scale:'aeolian'},
   why:'A bass ostinato that barely changes for the entire track, with everything else layered on top. Fox reused the theme across projects for years before it landed here.',
   listen:'The bass figure never lets up. The tension comes from repetition and accumulating layers rather than from harmonic movement.'},
  {id:'undertale-hopes', t:'Hopes and Dreams', g:'Undertale', c:'Toby Fox', y:2015, sys:'PC', era:'modern',
   dev:'Major · leitmotif recombination', link:{prog:'axis'},
   why:'Built from themes introduced earlier in the game, brought back in major at the emotional peak. The technique is Wagnerian; the delivery is chiptune-adjacent.',
   listen:'Melodies you have already heard elsewhere returning transformed. Recognition is the effect being engineered.'},
  {id:'persona-mass-destruction', t:'Mass Destruction', g:'Persona 3', c:'Shoji Meguro', y:2006, sys:'PS2', era:'modern',
   dev:'Acid jazz · minor 7th vamp', link:{chord:'m7'},
   why:'Meguro fused hip-hop rhythm with jazz-derived chord voicings and put it in a battle theme, which reset expectations for what an RPG fight could sound like.',
   listen:'Extended chords over a hard backbeat. The harmony is lounge; the drums absolutely are not.'},
  {id:'mario-galaxy', t:'Gusty Garden Galaxy', g:'Super Mario Galaxy', c:'Mahito Yokota', y:2007, sys:'Wii', era:'modern',
   dev:'Soaring lines · orchestral lift', link:{scale:'lydian'},
   why:'Yokota initially scored the game with Latin-flavoured music; Miyamoto asked for a full orchestra instead. The rewrite produced one of the most beloved cues in the series.',
   listen:'The melody keeps reaching upward and the harmony keeps catching it. Flight written for strings.'},
  {id:'okami-theme', t:'The Sun Rises', g:'Ōkami', c:'Masami Ueda and team', y:2006, sys:'PS2', era:'modern',
   dev:'Japanese pentatonic · taiko', link:{scale:'majpent-jp'},
   why:'Traditional Japanese instrumentation and scale material used because the game is drawn as a sumi-e ink painting — the music and the art are quoting the same tradition.',
   listen:'The gaps between notes. Traditional Japanese scoring treats silence as material, not as absence.'},
  {id:'sekiro-ashina', t:'Ashina Reservoir', g:'Sekiro: Shadows Die Twice', c:'Yuka Kitamura', y:2019, sys:'PS4', era:'modern',
   dev:'Japanese scale material · sparse texture', link:{scale:'majpent-jp'},
   why:'Traditional instruments scored with modern restraint. Kitamura writes very little and lets the silence and the room do most of the work.',
   listen:'How few notes are actually played. Tension is built from space and attack, not density.'},
  {id:'hollow-knight-dirtmouth', t:'Dirtmouth', g:'Hollow Knight', c:'Christopher Larkin', y:2017, sys:'PC', era:'modern',
   dev:'Solo piano · minor with open 5ths', link:{scale:'aeolian'},
   why:'One piano, played quietly, in a game otherwise full of orchestral menace. The restraint is what makes the town feel like the last safe place.',
   listen:'The pauses. Larkin lets phrases end and leaves the silence there rather than filling it.'},
  {id:'nier-ancients', t:'Song of the Ancients', g:'NieR', c:'Keiichi Okabe', y:2010, sys:'PS3', era:'modern',
   dev:'Modal vocal · invented language', link:{scale:'aeolian'},
   why:'Sung in a constructed language so no listener can understand the words. The voice becomes pure timbre and melodic contour with no semantic layer at all.',
   listen:'You are hearing a voice as an instrument. Without meaning to decode, you track the melody instead.'},
  {id:'celeste-first-steps', t:'First Steps', g:'Celeste', c:'Lena Raine', y:2018, sys:'PC', era:'modern',
   dev:'Piano ostinato · additive layering', link:{prog:'axis'},
   why:'Starts with a simple repeating piano figure and adds layers as the level continues. The music grows with the player\u2019s competence rather than the plot.',
   listen:'Each new layer arrives without changing the underlying loop. Addition, not modulation.'},
  {id:'animal-crossing', t:'Hourly Themes', g:'Animal Crossing', c:'Kazumi Totaka', y:2001, sys:'GameCube', era:'modern',
   dev:'Pentatonic ease · jazz voicings', link:{scale:'majpent'},
   why:'Twenty-four separate cues, one per hour, each written to feel like the time of day it represents. Simple melodies over surprisingly sophisticated chords.',
   listen:'The chords are far more complex than the tunes sitting on them. That gap is why it feels relaxed rather than childish.'}
];

/* ---- SOUND HARDWARE ---- the constraint that shaped the writing ---- */
OT.CHIPS = [
  {id:'2a03', n:'Ricoh 2A03', sys:'NES / Famicom', y:1983, ch:'5 channels',
   spec:['2 × pulse (square) with 4 duty cycles','1 × triangle, fixed volume','1 × noise','1 × 7-bit sample (DPCM)'],
   why:'Two melodic voices, one bass triangle and a noise channel for drums. Every famous NES melody was written knowing that if you wanted harmony, you gave up a countermelody.',
   trick:'Composers faked chords with arpeggios so fast they fuse into one sound — the ringing texture people associate with 8-bit music is a workaround for having too few channels.'},
  {id:'gb', n:'Game Boy DMG', sys:'Game Boy', y:1989, ch:'4 channels',
   spec:['2 × pulse','1 × 4-bit programmable wavetable','1 × noise'],
   why:'The wavetable channel let composers draw their own waveform, so the Game Boy could produce timbres the NES could not — at the cost of one fewer melodic voice.',
   trick:'The wave channel was often used for bass because a custom waveform could be made rounder and fuller than a square wave.'},
  {id:'ym2612', n:'Yamaha YM2612', sys:'Sega Genesis / Mega Drive', y:1988, ch:'6 FM + PSG',
   spec:['6 × 4-operator FM synthesis','1 channel switchable to 8-bit PCM','3 × square + 1 noise (SN76489)'],
   why:'FM synthesis builds timbre by having oscillators modulate each other. It excels at metallic, punchy, aggressive sounds — which is exactly why Genesis music has that distinctive bite.',
   trick:'The famous Genesis "slap bass" is FM doing something sampling could not afford in 1988: a complex evolving attack from pure math, with no sample memory used at all.'},
  {id:'spc700', n:'Sony SPC700 + S-DSP', sys:'Super Nintendo', y:1990, ch:'8 sample channels',
   spec:['8 × ADPCM sample voices at ~32 kHz','64 KB total audio RAM','BRR compression at roughly 32:9','Hardware echo, ADSR, pitch modulation, noise'],
   why:'A sampler rather than a synthesiser. Composers could use any sound they could fit — but every instrument, the sequence data and the sound driver all had to share 64 KB.',
   trick:'The hardware echo buffer eats audio RAM as delay time increases, so a lush reverb literally cost you instruments. David Wise\u2019s underwater themes spend that budget deliberately.'},
  {id:'ps1', n:'PlayStation SPU', sys:'PlayStation', y:1994, ch:'24 channels',
   spec:['24 × ADPCM voices','512 KB sound RAM','Hardware reverb','CD audio streaming'],
   why:'Three times the voices and eight times the memory of the SNES, plus the option to stream finished audio from the disc. This is where game scores stopped being chip music.',
   trick:'Streaming from CD meant no channel limit at all — but it cost disc bandwidth and could not react to gameplay, so composers kept using the sequenced voices for anything interactive.'}
];
