(()=>{'use strict';
const {createClient}=supabase;
const sb=createClient('https://xvfgiaxxvwdnmzzdfboc.supabase.co','sb_publishable_ShdZijibR7b6EvowZ1yN9Q_dIkGmcCZ');
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(Number(n||0));
let session=null,profile=null,auction=null,spots=[],selectedSpot=null,builder={auction:null,spots:[],selected:-1,imageUrl:null};
let toastT;function toast(m){const t=$('#toast');t.textContent=m;t.classList.add('on');clearTimeout(toastT);toastT=setTimeout(()=>t.classList.remove('on'),2200)}
function openModal(id){$('#scrim').classList.add('on');$(id).classList.add('on')}
function closePanels(){$('#scrim').classList.remove('on');$$('.panel').forEach(x=>x.classList.remove('on'))}
$$('[data-close]').forEach(b=>b.onclick=closePanels);$('#scrim').onclick=closePanels;

async function loadSession(){const {data}=await sb.auth.getSession();session=data.session;await loadProfile();syncAccount()}
async function loadProfile(){profile=null;if(!session)return;const {data}=await sb.from('profiles').select('*').eq('id',session.user.id).maybeSingle();profile=data||null}
function syncAccount(){const btn=$('#accountBtn');btn.textContent=session?(profile?.display_name||profile?.username||'ACCOUNT'):'SIGN IN';$('#adminNav').hidden=profile?.role!=='admin';$('#adminWrap').classList.toggle('on',profile?.role==='admin');if(profile?.role==='admin')loadAdmin();}
$('#accountBtn').onclick=()=>{openModal('#authModal');renderAccountModal()};
function renderAccountModal(){const signed=!!session;$('.auth-switch').hidden=signed;$('#authEmail').parentElement.hidden=signed;$('#authPassword').parentElement.hidden=signed;$('#displayField').hidden=true;$('#authSubmit').hidden=signed;$('#accountArea').hidden=!signed;if(signed){$('#accountEmail').textContent=`Signed in as ${session.user.email} · ${profile?.role==='admin'?'ADMIN':'BIDDER'}`;$('#profileUsername').value=profile?.username||'';$('#profileDisplay').value=profile?.display_name||'';$('#profileCompany').value=profile?.company_name||'';$('#profileWebsite').value=profile?.website||'';}}
let authMode='signin';$$('[data-auth]').forEach(b=>b.onclick=()=>{authMode=b.dataset.auth;$$('[data-auth]').forEach(x=>x.classList.toggle('active',x===b));$('#displayField').hidden=authMode!=='signup';$('#authSubmit').textContent=authMode==='signup'?'CREATE ACCOUNT':'SIGN IN'});
$('#authSubmit').onclick=async()=>{const email=$('#authEmail').value.trim(),password=$('#authPassword').value;try{if(authMode==='signup'){const {error}=await sb.auth.signUp({email,password,options:{data:{display_name:$('#authDisplay').value.trim()}}});if(error)throw error;toast('Account created. Check your email if confirmation is enabled.')}else{const {error}=await sb.auth.signInWithPassword({email,password});if(error)throw error;toast('Signed in');}}catch(e){toast(e.message)}};
$('#signOut').onclick=async()=>{await sb.auth.signOut();closePanels()};
$('#saveProfile').onclick=async()=>{if(!session)return;const payload={username:$('#profileUsername').value.trim(),display_name:$('#profileDisplay').value.trim(),company_name:$('#profileCompany').value.trim(),website:$('#profileWebsite').value.trim()};const {error}=await sb.from('profiles').update(payload).eq('id',session.user.id);if(error)return toast(error.message);await loadProfile();syncAccount();toast('Profile saved')};
$('#ownerSetup').onclick=()=>{closePanels();openModal('#ownerModal')};
$('#claimOwner').onclick=async()=>{if(!session)return toast('Sign in first');const {data,error}=await sb.rpc('claim_spot_owner',{p_code:$('#ownerCode').value.trim()});if(error)return toast(error.message);if(!data)return toast('Owner code rejected or already claimed');await loadProfile();syncAccount();closePanels();toast('SPOT admin activated')};
sb.auth.onAuthStateChange(async(_event,s)=>{session=s;await loadProfile();syncAccount();renderAccountModal()});

async function loadMarket(){const {data:auctions,error}=await sb.from('auctions').select('*').in('status',['live','upcoming']).order('starts_at',{ascending:true});if(error){toast(error.message);return}auction=(auctions||[]).find(a=>a.status==='live')||auctions?.[0]||null;if(!auction){renderNoAuction();return}const {data:market,error:merr}=await sb.from('spot_market').select('*').eq('auction_id',auction.id).order('spot_number');if(merr){toast(merr.message);return}spots=market||[];renderAuction();subscribeMarket();}
function renderNoAuction(){$('#auctionLabel').textContent='NO LIVE AUCTION';$('#objectName').textContent='NEXT OBJECT COMING SOON';$('#marketList').innerHTML='<div class="empty">No live auction right now.</div>';$('#spotCount').textContent='0';$('#totalBid').textContent='$0';$('#bidCount').textContent='0';$('#endsIn').textContent='—'}
function renderAuction(){$('#auctionLabel').textContent=auction.title.toUpperCase();$('#objectName').textContent=auction.object_name.toUpperCase();$('#heroDesc').textContent=auction.description||'Bid on a real placement.';const surface=$('#objectSurface');surface.innerHTML=auction.object_image_url?`<img src="${auction.object_image_url}" alt="${escapeHtml(auction.object_name)}">`:'<div class="fallback-object"></div>';spots.forEach(s=>{const b=document.createElement('button');b.className='spot';b.style.left=s.x_pct+'%';b.style.top=s.y_pct+'%';b.style.width=s.width_pct+'%';b.style.height=s.height_pct+'%';b.dataset.id=s.id;b.innerHTML=`<span class="n">${String(s.spot_number).padStart(2,'0')}</span><span class="brand">${escapeHtml(s.leading_brand||'AVAILABLE')}</span><span class="bid">${money(s.current_bid)}</span>`;b.onclick=()=>openBid(s.id);surface.appendChild(b)});$('#marketList').innerHTML=spots.map(s=>`<div class="market-row" data-id="${s.id}"><span class="num">${String(s.spot_number).padStart(2,'0')}</span><div><b>${escapeHtml(s.leading_brand||'OPEN')}</b><small>${escapeHtml(s.position_label||'Placement')} · ${s.bid_count||0} bids</small></div><b>${money(s.current_bid)}</b></div>`).join('');$$('.market-row').forEach(r=>r.onclick=()=>openBid(r.dataset.id));$('#spotCount').textContent=`${spots.length}`;$('#totalBid').textContent=money(spots.reduce((n,s)=>n+Number(s.current_bid||0),0));$('#bidCount').textContent=spots.reduce((n,s)=>n+Number(s.bid_count||0),0);tickCountdown();loadPast();}
function tickCountdown(){if(!auction?.ends_at){$('#endsIn').textContent='—';return}const ms=new Date(auction.ends_at)-Date.now();if(ms<=0){$('#endsIn').textContent='ENDED';return}const d=Math.floor(ms/86400000),h=Math.floor(ms/3600000)%24,m=Math.floor(ms/60000)%60;$('#endsIn').textContent=`${d}D ${h}H ${m}M`}
setInterval(tickCountdown,30000);
let channel;function subscribeMarket(){if(channel)sb.removeChannel(channel);channel=sb.channel('spot-live').on('postgres_changes',{event:'*',schema:'public',table:'bids'},()=>loadMarket()).on('postgres_changes',{event:'*',schema:'public',table:'auction_spots'},()=>loadMarket()).on('postgres_changes',{event:'*',schema:'public',table:'auctions'},()=>loadMarket()).subscribe()}

async function openBid(id){selectedSpot=spots.find(s=>s.id===id);if(!selectedSpot)return;$('#drawerSpot').textContent=`Spot ${String(selectedSpot.spot_number).padStart(2,'0')}`;$('#drawerSpotLabel').textContent=selectedSpot.position_label||'PLACEMENT';$('#currentBid').textContent=money(selectedSpot.current_bid);$('#leadingBrand').textContent=selectedSpot.leading_brand?`Leading: ${selectedSpot.leading_brand}`:'No bids yet';const next=Number(selectedSpot.current_bid)+(Number(selectedSpot.bid_count)>0?Number(selectedSpot.min_increment):0);$('#bidAmount').value=next;$('#bidRule').textContent=`Minimum next bid: ${money(next)} · increment ${money(selectedSpot.min_increment)}`;$('#brandName').value=profile?.company_name||'';$('#logoPreview').textContent='YOUR LOGO PREVIEW';$('#scrim').classList.add('on');$('#bidDrawer').classList.add('on')}
$('#logoUpload').onchange=e=>{const f=e.target.files?.[0];if(!f)return;const u=URL.createObjectURL(f);$('#logoPreview').innerHTML=`<img src="${u}" alt="logo preview">`};
async function uploadBrandLogo(file){if(!file||!session)return null;const ext=(file.name.split('.').pop()||'png').toLowerCase();const path=`${session.user.id}/${crypto.randomUUID()}.${ext}`;const {error}=await sb.storage.from('spot-brand-logos').upload(path,file,{upsert:false});if(error)throw error;return sb.storage.from('spot-brand-logos').getPublicUrl(path).data.publicUrl}
$('#placeBidBtn').onclick=async()=>{if(!session){closePanels();openModal('#authModal');renderAccountModal();return}if(!selectedSpot)return;try{const brand=$('#brandName').value.trim();if(!brand)return toast('Enter your brand name');let logo=null;const f=$('#logoUpload').files?.[0];if(f)logo=await uploadBrandLogo(f);const {error}=await sb.rpc('place_bid',{p_spot_id:selectedSpot.id,p_amount:Number($('#bidAmount').value),p_brand_name:brand,p_logo_url:logo});if(error)throw error;toast('Bid accepted');closePanels();await loadMarket()}catch(e){toast(e.message)}};

async function loadPast(){const {data}=await sb.from('auctions').select('*').in('status',['ended','archived']).order('ends_at',{ascending:false});$('#archives').innerHTML=(data||[]).length?(data||[]).map(a=>`<article class="archive-card"><span>${a.status.toUpperCase()}</span><h3>${escapeHtml(a.title)}</h3><p>${escapeHtml(a.object_name)}${a.proof_image_url?' · proof uploaded':''}</p><button class="secondary">VIEW ARCHIVE</button></article>`).join(''):'<div class="empty">Completed auctions will live here permanently.</div>'}
function setView(v){$('#liveView').hidden=v!=='live';$('#pastView').hidden=v!=='past';if(v==='past')loadPast();$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===v))}
$$('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));

/* ADMIN */
$('#adminNav').onclick=()=>{$('#adminWrap').scrollIntoView({behavior:'smooth'});loadAdmin()};
async function loadAdmin(){if(profile?.role!=='admin')return;const {data}=await sb.from('auctions').select('*,auction_spots(count)').order('created_at',{ascending:false});$('#adminAuctions').innerHTML=(data||[]).map(a=>`<div class="spot-admin-row"><span>${a.status==='live'?'●':'○'}</span><div><b>${escapeHtml(a.title)}</b><small style="display:block;color:#666">${escapeHtml(a.object_name)} · ${a.auction_spots?.[0]?.count||0} spots</small></div><button class="secondary" data-edit-auction="${a.id}">EDIT</button></div>`).join('');$$('[data-edit-auction]').forEach(b=>b.onclick=()=>editAuction(b.dataset.editAuction))}
$('#newAuctionBtn').onclick=()=>{builder={auction:null,spots:[],selected:-1,imageUrl:null};$('#builderCard').hidden=false;['aTitle','aSlug','aObject','aDesc'].forEach(id=>$('#'+id).value='');$('#aStatus').value='draft';$('#aStarts').value='';$('#aEnds').value='';$('#builderSurface').innerHTML='<span style="position:absolute;inset:0;display:grid;place-items:center;color:#444;pointer-events:none">UPLOAD OBJECT PHOTO · THEN CLICK TO PLACE SPOTS</span>';renderBuilderSpots()};
async function editAuction(id){const {data:a}=await sb.from('auctions').select('*').eq('id',id).single();const {data:ss}=await sb.from('auction_spots').select('*').eq('auction_id',id).order('spot_number');builder={auction:a,spots:ss||[],selected:-1,imageUrl:a.object_image_url||null};$('#builderCard').hidden=false;$('#aTitle').value=a.title;$('#aSlug').value=a.slug;$('#aObject').value=a.object_name;$('#aDesc').value=a.description||'';$('#aStatus').value=a.status;$('#aStarts').value=toLocal(a.starts_at);$('#aEnds').value=toLocal(a.ends_at);renderBuilderSurface();renderBuilderSpots();$('#builderCard').scrollIntoView({behavior:'smooth'})}
function toLocal(x){if(!x)return'';const d=new Date(x),p=n=>String(n).padStart(2,'0');return`${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}T${p(d.getHours())}:${p(d.getMinutes())}`}
$('#objectUpload').onchange=async e=>{const f=e.target.files?.[0];if(!f)return;try{const ext=(f.name.split('.').pop()||'jpg').toLowerCase();const path=`objects/${crypto.randomUUID()}.${ext}`;const {error}=await sb.storage.from('spot-auction-images').upload(path,f);if(error)throw error;builder.imageUrl=sb.storage.from('spot-auction-images').getPublicUrl(path).data.publicUrl;renderBuilderSurface()}catch(err){toast(err.message)}};
function renderBuilderSurface(){const s=$('#builderSurface');s.innerHTML=builder.imageUrl?`<img src="${builder.imageUrl}" alt="object preview">`:'';builder.spots.forEach((x,i)=>{const m=document.createElement('div');m.className='builder-marker';m.style.left=x.x_pct+'%';m.style.top=x.y_pct+'%';m.style.width=x.width_pct+'%';m.style.height=x.height_pct+'%';m.style.borderColor=i===builder.selected?'#ff7a45':'#c8ff2e';s.appendChild(m)})}
$('#builderSurface').onclick=e=>{const r=e.currentTarget.getBoundingClientRect();const x=((e.clientX-r.left)/r.width)*100,y=((e.clientY-r.top)/r.height)*100;builder.spots.push({spot_number:builder.spots.length+1,position_label:`Spot ${builder.spots.length+1}`,size_label:'Custom',x_pct:Math.max(0,x-9),y_pct:Math.max(0,y-7),width_pct:18,height_pct:14,starting_bid:100,min_increment:10,premium:false,status:'open'});builder.selected=builder.spots.length-1;renderBuilderSurface();renderBuilderSpots();syncSelectedFields()};
$('#addSpotBtn').onclick=()=>{builder.spots.push({spot_number:builder.spots.length+1,position_label:`Spot ${builder.spots.length+1}`,size_label:'Custom',x_pct:41,y_pct:43,width_pct:18,height_pct:14,starting_bid:100,min_increment:10,premium:false,status:'open'});builder.selected=builder.spots.length-1;renderBuilderSurface();renderBuilderSpots();syncSelectedFields()};
function renderBuilderSpots(){$('#adminSpots').innerHTML=builder.spots.map((s,i)=>`<div class="spot-admin-row" data-builder-spot="${i}"><span>${String(s.spot_number).padStart(2,'0')}</span><div><b>${escapeHtml(s.position_label||'Placement')}</b><small style="display:block;color:#666">${s.x_pct.toFixed?.(1)||s.x_pct}%, ${s.y_pct.toFixed?.(1)||s.y_pct}%</small></div><button class="danger" data-del-spot="${i}">×</button></div>`).join('');$$('[data-builder-spot]').forEach(r=>r.onclick=e=>{if(e.target.closest('[data-del-spot]'))return;builder.selected=+r.dataset.builderSpot;syncSelectedFields();renderBuilderSurface()});$$('[data-del-spot]').forEach(b=>b.onclick=e=>{e.stopPropagation();builder.spots.splice(+b.dataset.delSpot,1);builder.spots.forEach((s,i)=>s.spot_number=i+1);builder.selected=-1;renderBuilderSpots();renderBuilderSurface()})}
function syncSelectedFields(){const s=builder.spots[builder.selected];if(!s)return;$('#spotPosition').value=s.position_label||'';$('#spotStart').value=s.starting_bid;$('#spotIncrement').value=s.min_increment;$('#spotW').value=s.width_pct;$('#spotH').value=s.height_pct}
['spotPosition','spotStart','spotIncrement','spotW','spotH'].forEach(id=>$('#'+id).oninput=()=>{const s=builder.spots[builder.selected];if(!s)return;s.position_label=$('#spotPosition').value;s.starting_bid=Number($('#spotStart').value)||0;s.min_increment=Number($('#spotIncrement').value)||10;s.width_pct=Math.max(1,Number($('#spotW').value)||18);s.height_pct=Math.max(1,Number($('#spotH').value)||14);renderBuilderSpots();renderBuilderSurface()});
$('#saveAuctionBtn').onclick=async()=>{if(profile?.role!=='admin')return;try{const payload={title:$('#aTitle').value.trim(),slug:$('#aSlug').value.trim(),object_name:$('#aObject').value.trim(),description:$('#aDesc').value.trim(),status:$('#aStatus').value,starts_at:$('#aStarts').value?new Date($('#aStarts').value).toISOString():null,ends_at:$('#aEnds').value?new Date($('#aEnds').value).toISOString():null,object_image_url:builder.imageUrl||null,created_by:session.user.id};if(!payload.title||!payload.slug||!payload.object_name)throw new Error('Title, slug and object name are required');let id=builder.auction?.id;if(id){const {error}=await sb.from('auctions').update(payload).eq('id',id);if(error)throw error;await sb.from('auction_spots').delete().eq('auction_id',id)}else{const {data,error}=await sb.from('auctions').insert(payload).select().single();if(error)throw error;id=data.id}if(builder.spots.length){const rows=builder.spots.map(s=>({...s,auction_id:id}));const {error}=await sb.from('auction_spots').insert(rows);if(error)throw error}toast('Auction saved');$('#builderCard').hidden=true;await loadAdmin();await loadMarket()}catch(e){toast(e.message)}};

function escapeHtml(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
loadSession();loadMarket();loadPast();
})();