(()=>{'use strict';
const {createClient}=supabase;
const sb=createClient('https://xvfgiaxxvwdnmzzdfboc.supabase.co','sb_publishable_ShdZijibR7b6EvowZ1yN9Q_dIkGmcCZ');
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(Number(n||0));
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
let session=null,profile=null,auction=null,spots=[],selectedSpot=null,channel=null;
let builder={auction:null,spots:[],selected:-1,imageUrl:null,proofUrl:null,originalIds:[]};
let toastTimer;function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('on');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('on'),2300)}
function openPanel(id){$('#scrim').classList.add('on');$(id).classList.add('on')}
function closePanels(){$('#scrim').classList.remove('on');$$('.panel').forEach(x=>x.classList.remove('on'))}
$$('[data-close]').forEach(b=>b.onclick=closePanels);$('#scrim').onclick=closePanels;

function setView(name){$$('.view').forEach(v=>v.classList.toggle('active',v.id===name+'View'));$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===name));if(name==='winners')loadPast();if(name==='admin'&&profile?.role==='admin')loadAdmin();scrollTo({top:0,behavior:'smooth'})}
$$('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));

async function loadSession(){const {data}=await sb.auth.getSession();session=data.session;await loadProfile();syncAccount()}
async function loadProfile(){profile=null;if(!session)return;const {data}=await sb.from('profiles').select('*').eq('id',session.user.id).maybeSingle();profile=data||null}
function syncAccount(){const btn=$('#accountBtn');btn.textContent=session?(profile?.display_name||profile?.username||'ACCOUNT'):'SIGN IN';btn.classList.toggle('signed',!!session);$('#adminNav').hidden=profile?.role!=='admin';$('#homeSignIn').hidden=!!session;}
$('#accountBtn').onclick=()=>{renderAccount();openPanel('#authModal')};$('#homeSignIn').onclick=()=>{renderAccount();openPanel('#authModal')};
let authMode='signin';
function renderAccount(){const signed=!!session;$('#authGuest').hidden=signed;$('#authAccount').hidden=!signed;if(signed){$('#accountEmail').textContent=`${session.user.email} · ${profile?.role==='admin'?'ADMIN':'BIDDER'}`;$('#profileUsername').value=profile?.username||'';$('#profileDisplay').value=profile?.display_name||'';$('#profileCompany').value=profile?.company_name||'';$('#profileWebsite').value=profile?.website||'';$('#ownerSetup').hidden=true;}}
$$('[data-auth]').forEach(b=>b.onclick=()=>{authMode=b.dataset.auth;$$('[data-auth]').forEach(x=>x.classList.toggle('active',x===b));$('#signupNameField').hidden=authMode!=='signup';$('#authSubmit').textContent=authMode==='signup'?'CREATE ACCOUNT':'SIGN IN'});
$('#authSubmit').onclick=async()=>{const email=$('#authEmail').value.trim(),password=$('#authPassword').value;if(!email||!password)return toast('Enter email and password');try{if(authMode==='signup'){const {error}=await sb.auth.signUp({email,password,options:{data:{display_name:$('#signupName').value.trim()}}});if(error)throw error;toast('Account created. Check your email if confirmation is required.')}else{const {data,error}=await sb.auth.signInWithPassword({email,password});if(error)throw error;session=data.session;await loadProfile();syncAccount();renderAccount();toast('Signed in');closePanels()}}catch(e){toast(e.message)}};
$('#forgotPassword').onclick=async()=>{const email=$('#authEmail').value.trim();if(!email)return toast('Enter your email first');const {error}=await sb.auth.resetPasswordForEmail(email,{redirectTo:location.origin+location.pathname});toast(error?error.message:'Password reset email sent')};
$('#signOut').onclick=async()=>{await sb.auth.signOut();closePanels();setView('home')};
$('#saveProfile').onclick=async()=>{if(!session)return;const payload={username:$('#profileUsername').value.trim(),display_name:$('#profileDisplay').value.trim(),company_name:$('#profileCompany').value.trim(),website:$('#profileWebsite').value.trim()};const {error}=await sb.from('profiles').update(payload).eq('id',session.user.id);if(error)return toast(error.message);await loadProfile();syncAccount();toast('Profile saved')};
$('#ownerSetup').onclick=()=>{closePanels();openPanel('#ownerModal')};
sb.auth.onAuthStateChange(async(_e,s)=>{session=s;await loadProfile();syncAccount();renderAccount()});

async function loadMarket(){const {data:auctions,error}=await sb.from('auctions').select('*').in('status',['live','upcoming']).order('starts_at',{ascending:true});if(error)return toast(error.message);auction=(auctions||[]).find(a=>a.status==='live')||(auctions||[])[0]||null;if(!auction){renderNoAuction();await loadPast();return}const {data,error:merr}=await sb.from('spot_market').select('*').eq('auction_id',auction.id).order('spot_number');if(merr)return toast(merr.message);spots=data||[];renderAuction();subscribe();await loadPast()}
function renderNoAuction(){$('#auctionLabel').textContent='NO LIVE AUCTION';$('#objectName').textContent='NEXT OBJECT COMING SOON';$('#auctionTitle').textContent='Nothing live right now.';$('#auctionDesc').textContent='The next object will appear here as soon as it is published.';$('#objectSurface').innerHTML='<div class="fallback-object">NEXT OBJECT</div>';$('#marketList').innerHTML='<div class="empty">No placements are open yet.</div>';$('#totalBid').textContent='$0';$('#spotCount').textContent='0';$('#bidCount').textContent='0';$('#endsIn').textContent='—'}
function renderAuction(){$('#auctionLabel').textContent=auction.status==='live'?'LIVE AUCTION':'UPCOMING';$('#objectName').textContent=auction.object_name.toUpperCase();$('#auctionTitle').textContent=auction.title;$('#auctionDesc').textContent=auction.description||'Bid on a real physical placement.';const surface=$('#objectSurface');surface.innerHTML=auction.object_image_url?`<img src="${auction.object_image_url}" alt="${esc(auction.object_name)}">`:'<div class="fallback-object">OBJECT PHOTO</div>';spots.forEach(s=>{const b=document.createElement('button');b.className='spot';b.style.left=s.x_pct+'%';b.style.top=s.y_pct+'%';b.style.width=s.width_pct+'%';b.style.height=s.height_pct+'%';b.innerHTML=`<span class="num">${String(s.spot_number).padStart(2,'0')}</span><span class="brand-name">${esc(s.leading_brand||'AVAILABLE')}</span><span class="price">${money(s.current_bid)}</span>`;b.onclick=()=>openBid(s.id);surface.appendChild(b)});$('#marketList').innerHTML=spots.length?spots.map(s=>`<button class="market-row" data-spot-id="${s.id}" style="border-left:0;border-right:0;border-top:0;background:none;color:inherit;width:100%;text-align:left"><span class="n">${String(s.spot_number).padStart(2,'0')}</span><span><strong>${esc(s.leading_brand||'OPEN')}</strong><small>${esc(s.position_label||'Placement')} · ${s.bid_count||0} bids</small></span><b>${money(s.current_bid)}</b></button>`).join(''):'<div class="empty">No placements added yet.</div>';$$('[data-spot-id]').forEach(x=>x.onclick=()=>openBid(x.dataset.spotId));$('#totalBid').textContent=money(spots.reduce((n,s)=>n+Number(s.current_bid||0),0));$('#spotCount').textContent=spots.length;$('#bidCount').textContent=spots.reduce((n,s)=>n+Number(s.bid_count||0),0);tickCountdown()}
function tickCountdown(){if(!auction?.ends_at){$('#endsIn').textContent='—';return}const ms=new Date(auction.ends_at)-Date.now();if(ms<=0){$('#endsIn').textContent='ENDED';return}const d=Math.floor(ms/86400000),h=Math.floor(ms/3600000)%24,m=Math.floor(ms/60000)%60;$('#endsIn').textContent=`${d}D ${h}H ${m}M`}
setInterval(tickCountdown,30000);
function subscribe(){if(channel)sb.removeChannel(channel);channel=sb.channel('spot-market-v3').on('postgres_changes',{event:'*',schema:'public',table:'bids'},loadMarket).on('postgres_changes',{event:'*',schema:'public',table:'auction_spots'},loadMarket).on('postgres_changes',{event:'*',schema:'public',table:'auctions'},loadMarket).subscribe()}

async function openBid(id){selectedSpot=spots.find(s=>s.id===id);if(!selectedSpot)return;$('#drawerSpot').textContent=`Spot ${String(selectedSpot.spot_number).padStart(2,'0')}`;$('#drawerPosition').textContent=selectedSpot.position_label||'PLACEMENT';$('#currentBid').textContent=money(selectedSpot.current_bid);$('#leadingBrand').textContent=selectedSpot.leading_brand?`Leading: ${selectedSpot.leading_brand}`:'No bids yet';const next=Number(selectedSpot.current_bid)+(Number(selectedSpot.bid_count)>0?Number(selectedSpot.min_increment):0);$('#bidAmount').value=next;$('#bidRule').textContent=`Minimum next bid ${money(next)} · ${money(selectedSpot.min_increment)} increment`;$('#brandName').value=profile?.company_name||'';$('#logoPreview').textContent='YOUR LOGO';$('#bidAuthNote').hidden=!!session;openPanel('#bidDrawer')}
$('#logoUpload').onchange=e=>{const f=e.target.files?.[0];if(!f)return;$('#logoPreview').innerHTML=`<img src="${URL.createObjectURL(f)}" alt="Logo preview">`};
async function uploadBrandLogo(file){if(!file||!session)return null;const ext=(file.name.split('.').pop()||'png').toLowerCase();const path=`${session.user.id}/${crypto.randomUUID()}.${ext}`;const {error}=await sb.storage.from('spot-brand-logos').upload(path,file);if(error)throw error;return sb.storage.from('spot-brand-logos').getPublicUrl(path).data.publicUrl}
$('#placeBidBtn').onclick=async()=>{if(!session){closePanels();renderAccount();openPanel('#authModal');return}if(!selectedSpot)return;try{const brand=$('#brandName').value.trim();if(!brand)return toast('Enter your brand name');let logo=null;const file=$('#logoUpload').files?.[0];if(file)logo=await uploadBrandLogo(file);const {error}=await sb.rpc('place_bid',{p_spot_id:selectedSpot.id,p_amount:Number($('#bidAmount').value),p_brand_name:brand,p_logo_url:logo});if(error)throw error;toast('Bid accepted');closePanels();await loadMarket()}catch(e){toast(e.message)}};

async function loadPast(){const {data:past,error}=await sb.from('auctions').select('*').in('status',['ended','archived']).order('ends_at',{ascending:false});if(error)return;const auctions= past||[];let market=[];if(auctions.length){const {data}=await sb.from('spot_market').select('*').in('auction_id',auctions.map(a=>a.id));market=data||[]}const grouped=Object.groupBy?Object.groupBy(market,x=>x.auction_id):market.reduce((g,x)=>((g[x.auction_id]??=[]).push(x),g),{});const cards=auctions.map(a=>winnerCard(a,grouped[a.id]||[]));$('#homeWinners').innerHTML=cards.length?cards.slice(0,3).join(''):'<div class="empty" style="grid-column:1/-1">Previous winners will appear here after the first auction ends.</div>';$('#allWinners').innerHTML=cards.length?cards.join(''):'<div class="empty" style="grid-column:1/-1">No completed auctions yet.</div>'}
function winnerCard(a,ss){const brands=ss.filter(s=>s.leading_brand).slice(0,6);const photo=a.proof_image_url||a.object_image_url;return`<article class="winner-card"><div class="winner-photo">${photo?`<img src="${photo}" alt="${esc(a.object_name)}">`:'<div class="no-photo">PROOF PHOTO PENDING</div>'}</div><div class="winner-body"><span>${a.proof_image_url?'IN THE WILD':'AUCTION COMPLETE'}</span><h3>${esc(a.title)}</h3><div class="winner-brands">${brands.length?brands.map(x=>`<i>${esc(x.leading_brand)}</i>`).join(''):'<i>Winners pending</i>'}</div></div></article>`}

/* ADMIN */
$('#adminNav').onclick=()=>setView('admin');$('#newAuctionBtn').onclick=newAuction;
function newAuction(){builder={auction:null,spots:[],selected:-1,imageUrl:null,proofUrl:null,originalIds:[]};$('#builderCard').hidden=false;['aTitle','aSlug','aObject','aDesc'].forEach(id=>$('#'+id).value='');$('#aStatus').value='draft';$('#aStarts').value='';$('#aEnds').value='';$('#objectUpload').value='';$('#proofUpload').value='';renderBuilder();$('#builderCard').scrollIntoView({behavior:'smooth'})}
async function loadAdmin(){if(profile?.role!=='admin')return;const {data}=await sb.from('auctions').select('*,auction_spots(count)').order('created_at',{ascending:false});$('#adminAuctions').innerHTML=(data||[]).length?(data||[]).map(a=>`<div class="admin-row"><span>${a.status==='live'?'●':'○'}</span><div><b>${esc(a.title)}</b><small>${esc(a.object_name)} · ${a.auction_spots?.[0]?.count||0} spots · ${a.status}</small></div><button class="secondary" data-edit="${a.id}">EDIT</button></div>`).join(''):'<div class="empty">No auctions yet.</div>';$$('[data-edit]').forEach(b=>b.onclick=()=>editAuction(b.dataset.edit))}
async function editAuction(id){const {data:a,error}=await sb.from('auctions').select('*').eq('id',id).single();if(error)return toast(error.message);const {data:ss}=await sb.from('auction_spots').select('*').eq('auction_id',id).order('spot_number');builder={auction:a,spots:(ss||[]).map(x=>({...x})),selected:-1,imageUrl:a.object_image_url||null,proofUrl:a.proof_image_url||null,originalIds:(ss||[]).map(x=>x.id)};$('#builderCard').hidden=false;$('#aTitle').value=a.title;$('#aSlug').value=a.slug;$('#aObject').value=a.object_name;$('#aDesc').value=a.description||'';$('#aStatus').value=a.status;$('#aStarts').value=toLocal(a.starts_at);$('#aEnds').value=toLocal(a.ends_at);renderBuilder();$('#builderCard').scrollIntoView({behavior:'smooth'})}
function toLocal(x){if(!x)return'';const d=new Date(x),p=n=>String(n).padStart(2,'0');return`${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}T${p(d.getHours())}:${p(d.getMinutes())}`}
async function uploadAdminImage(bucket,file,prefix){if(!file)return null;const ext=(file.name.split('.').pop()||'jpg').toLowerCase();const path=`${prefix}/${crypto.randomUUID()}.${ext}`;const {error}=await sb.storage.from(bucket).upload(path,file);if(error)throw error;return sb.storage.from(bucket).getPublicUrl(path).data.publicUrl}
$('#objectUpload').onchange=async e=>{const file=e.target.files?.[0];if(!file)return;try{builder.imageUrl=await uploadAdminImage('spot-auction-images',file,'objects');renderBuilderSurface();toast('Object photo uploaded')}catch(err){toast(err.message)}};
$('#proofUpload').onchange=async e=>{const file=e.target.files?.[0];if(!file)return;try{builder.proofUrl=await uploadAdminImage('spot-proof-images',file,'proof');toast('Proof photo uploaded')}catch(err){toast(err.message)}};
$('#addSpotBtn').onclick=()=>{if(!builder.imageUrl)return toast('Upload the object photo first');const i=builder.spots.length;builder.spots.push({spot_number:i+1,position_label:`Placement ${i+1}`,size_label:'Custom',x_pct:41,y_pct:43,width_pct:18,height_pct:14,starting_bid:100,min_increment:10,premium:false,status:'open'});builder.selected=i;renderBuilder();syncSpotEditor()};
function renderBuilder(){renderBuilderSurface();renderSpotList();syncSpotEditor()}
function renderBuilderSurface(){const s=$('#builderSurface');s.innerHTML=builder.imageUrl?`<img src="${builder.imageUrl}" alt="Object preview">`:'<div class="builder-empty">1. UPLOAD YOUR OBJECT PHOTO<br><br>2. CLICK “ADD LOGO SPOT”<br><br>3. DRAG + RESIZE THE BOXES</div>';builder.spots.forEach((x,i)=>{const m=document.createElement('div');m.className='builder-marker'+(i===builder.selected?' selected':'');m.dataset.index=i;m.style.left=x.x_pct+'%';m.style.top=x.y_pct+'%';m.style.width=x.width_pct+'%';m.style.height=x.height_pct+'%';m.innerHTML=`SPOT ${String(x.spot_number).padStart(2,'0')}<i class="resize-handle" data-resize></i>`;m.onpointerdown=startMarkerPointer;s.appendChild(m)})}
let pointer=null;function startMarkerPointer(e){e.preventDefault();e.stopPropagation();const marker=e.currentTarget,index=+marker.dataset.index,item=builder.spots[index],rect=$('#builderSurface').getBoundingClientRect();builder.selected=index;syncSpotEditor();renderSpotList();marker.classList.add('selected');pointer={mode:e.target.matches('[data-resize]')?'resize':'drag',index,startX:e.clientX,startY:e.clientY,x:Number(item.x_pct),y:Number(item.y_pct),w:Number(item.width_pct),h:Number(item.height_pct),rect};marker.setPointerCapture?.(e.pointerId)}
addEventListener('pointermove',e=>{if(!pointer)return;const s=builder.spots[pointer.index],dx=(e.clientX-pointer.startX)/pointer.rect.width*100,dy=(e.clientY-pointer.startY)/pointer.rect.height*100;if(pointer.mode==='drag'){s.x_pct=clamp(pointer.x+dx,0,100-s.width_pct);s.y_pct=clamp(pointer.y+dy,0,100-s.height_pct)}else{s.width_pct=clamp(pointer.w+dx,5,100-s.x_pct);s.height_pct=clamp(pointer.h+dy,5,100-s.y_pct)}const m=$(`.builder-marker[data-index="${pointer.index}"]`);if(m){m.style.left=s.x_pct+'%';m.style.top=s.y_pct+'%';m.style.width=s.width_pct+'%';m.style.height=s.height_pct+'%'}syncSpotEditorValues();});addEventListener('pointerup',()=>{if(!pointer)return;pointer=null;renderSpotList()});
function clamp(v,min,max){return Math.min(max,Math.max(min,v))}
function renderSpotList(){$('#adminSpots').innerHTML=builder.spots.length?builder.spots.map((s,i)=>`<div class="spot-row ${i===builder.selected?'selected':''}" data-select="${i}"><span>${String(s.spot_number).padStart(2,'0')}</span><div><b>${esc(s.position_label||'Placement')}</b><small>${Number(s.width_pct).toFixed(0)}% × ${Number(s.height_pct).toFixed(0)}%</small></div><button class="mini-delete" data-remove="${i}">×</button></div>`).join(''):'<div class="empty">No logo spots yet.</div>';$$('[data-select]').forEach(r=>r.onclick=e=>{if(e.target.closest('[data-remove]'))return;builder.selected=+r.dataset.select;renderBuilder();syncSpotEditor()});$$('[data-remove]').forEach(b=>b.onclick=e=>{e.stopPropagation();const i=+b.dataset.remove;builder.spots.splice(i,1);builder.spots.forEach((x,n)=>x.spot_number=n+1);builder.selected=-1;renderBuilder()})}
function syncSpotEditor(){const s=builder.spots[builder.selected],box=$('#spotEditor');box.classList.toggle('disabled',!s);if(!s)return;$('#spotPosition').value=s.position_label||'';$('#spotStart').value=s.starting_bid;$('#spotIncrement').value=s.min_increment;$('#spotW').value=Number(s.width_pct).toFixed(1);$('#spotH').value=Number(s.height_pct).toFixed(1)}
function syncSpotEditorValues(){const s=builder.spots[builder.selected];if(!s)return;$('#spotW').value=Number(s.width_pct).toFixed(1);$('#spotH').value=Number(s.height_pct).toFixed(1)}
['spotPosition','spotStart','spotIncrement','spotW','spotH'].forEach(id=>$('#'+id).oninput=()=>{const s=builder.spots[builder.selected];if(!s)return;s.position_label=$('#spotPosition').value;s.starting_bid=Number($('#spotStart').value)||0;s.min_increment=Math.max(1,Number($('#spotIncrement').value)||10);s.width_pct=clamp(Number($('#spotW').value)||5,5,100-s.x_pct);s.height_pct=clamp(Number($('#spotH').value)||5,5,100-s.y_pct);renderBuilderSurface();renderSpotList()});
$('#saveAuctionBtn').onclick=saveAuction;
async function saveAuction(){if(profile?.role!=='admin')return;const title=$('#aTitle').value.trim(),slug=$('#aSlug').value.trim().toLowerCase().replace(/[^a-z0-9-]+/g,'-'),objectName=$('#aObject').value.trim();if(!title||!slug||!objectName)return toast('Title, slug and object name are required');if(!builder.imageUrl)return toast('Upload an object photo');if(!builder.spots.length)return toast('Add at least one logo spot');const payload={title,slug,object_name:objectName,description:$('#aDesc').value.trim(),status:$('#aStatus').value,starts_at:$('#aStarts').value?new Date($('#aStarts').value).toISOString():null,ends_at:$('#aEnds').value?new Date($('#aEnds').value).toISOString():null,object_image_url:builder.imageUrl,proof_image_url:builder.proofUrl};try{let auctionId;if(builder.auction){const {error}=await sb.from('auctions').update(payload).eq('id',builder.auction.id);if(error)throw error;auctionId=builder.auction.id}else{const {data,error}=await sb.from('auctions').insert({...payload,created_by:session.user.id}).select().single();if(error)throw error;auctionId=data.id;builder.auction=data}const currentIds=[];for(const s of builder.spots){const row={auction_id:auctionId,spot_number:s.spot_number,position_label:s.position_label||`Placement ${s.spot_number}`,size_label:s.size_label||'Custom',x_pct:+Number(s.x_pct).toFixed(3),y_pct:+Number(s.y_pct).toFixed(3),width_pct:+Number(s.width_pct).toFixed(3),height_pct:+Number(s.height_pct).toFixed(3),starting_bid:Number(s.starting_bid),min_increment:Number(s.min_increment),premium:!!s.premium,status:s.status||'open'};if(s.id){const {error}=await sb.from('auction_spots').update(row).eq('id',s.id);if(error)throw error;currentIds.push(s.id)}else{const {data,error}=await sb.from('auction_spots').insert(row).select().single();if(error)throw error;s.id=data.id;currentIds.push(data.id)}}if(builder.originalIds.length&&['draft','upcoming'].includes(payload.status)){const removed=builder.originalIds.filter(id=>!currentIds.includes(id));if(removed.length){const {error}=await sb.from('auction_spots').delete().in('id',removed);if(error)throw error}}builder.originalIds=[...currentIds];toast('Auction saved');await loadAdmin();await loadMarket()}catch(e){toast(e.message)}}

loadSession().then(loadMarket);
})();