(()=>{
'use strict';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=new Intl.NumberFormat('en-US',{maximumFractionDigits:0});
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(Number(n)||0);
const state={from:null,to:null,fromWeather:null,toWeather:null,route:null,map:null,layers:[],climate:{from:null,to:null}};
let toastT;
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('on');clearTimeout(toastT);toastT=setTimeout(()=>t.classList.remove('on'),1900)}

/* boot */
const boot=$('#boot');const leaveBoot=()=>{if(!boot)return;boot.classList.add('out');setTimeout(()=>boot.remove(),500)};
if(document.readyState==='complete')setTimeout(leaveBoot,1050);else window.addEventListener('load',()=>setTimeout(leaveBoot,720),{once:true});setTimeout(leaveBoot,2400);

/* location search */
const resolved={from:null,to:null};
setupSearch('fromInput','fromSuggestions','fromResolved','from');setupSearch('toInput','toSuggestions','toResolved','to');
function setupSearch(inputId,listId,statusId,side){const input=$('#'+inputId),list=$('#'+listId);let timer=0,seq=0;
 input.addEventListener('input',()=>{resolved[side]=null;$('#'+statusId).textContent='Searching…';clearTimeout(timer);const q=input.value.trim();if(q.length<2){list.classList.remove('on');$('#'+statusId).textContent='Search a city or ZIP code';return}const my=++seq;timer=setTimeout(async()=>{try{const a=await searchLocations(q);if(my!==seq)return;renderSuggestions(a,list,side,input,statusId)}catch(e){list.classList.remove('on');$('#'+statusId).textContent='Search unavailable — try again'}},260)});
 input.addEventListener('focus',()=>{if(list.children.length)list.classList.add('on')});
 document.addEventListener('click',e=>{if(!e.target.closest('.'+(side==='from'?'from-field':'to-field')))list.classList.remove('on')});
}
async function searchLocations(q){const r=await fetch(`https://geocoding-api.open-meteo.com/v1/search?name=${encodeURIComponent(q)}&count=7&language=en&format=json`);if(!r.ok)throw new Error('Geocoding failed');const j=await r.json();return j.results||[]}
function locLabel(x){return [x.name,x.admin1,x.country_code].filter(Boolean).join(', ')}
function renderSuggestions(a,list,side,input,statusId){if(!a.length){list.innerHTML='<button type="button"><b>No locations found</b><span>Try city + state or a ZIP code</span></button>';list.classList.add('on');return}list.innerHTML=a.map((x,i)=>`<button type="button" data-i="${i}"><b>${esc(x.name)}</b><span>${esc([x.admin1,x.country,x.postcodes?.[0]].filter(Boolean).join(' · '))}</span></button>`).join('');list.classList.add('on');list.onclick=e=>{const b=e.target.closest('button[data-i]');if(!b)return;const x=a[+b.dataset.i];resolved[side]=x;input.value=locLabel(x);$('#'+statusId).textContent=`${Number(x.latitude).toFixed(3)}, ${Number(x.longitude).toFixed(3)} · ${x.timezone||'timezone —'}`;list.classList.remove('on')}}
$$('.clear-field').forEach(b=>b.addEventListener('click',()=>{const id=b.dataset.clear,side=id.startsWith('from')?'from':'to';$('#'+id).value='';resolved[side]=null;$('#'+(side==='from'?'fromResolved':'toResolved')).textContent='Search a city or ZIP code';$('#'+id).focus()}));
async function resolveInput(side){if(resolved[side])return resolved[side];const q=$('#'+(side==='from'?'fromInput':'toInput')).value.trim();if(!q)throw new Error(`Enter a ${side==='from'?'current':'destination'} location`);const a=await searchLocations(q);if(!a.length)throw new Error(`Could not resolve ${q}`);resolved[side]=a[0];return a[0]}

$('#routeForm').addEventListener('submit',e=>{e.preventDefault();buildBrief()});
$('#sampleMove').addEventListener('click',async()=>{$('#fromInput').value='Paris, Texas';$('#toInput').value='Nashville, Tennessee';resolved.from=null;resolved.to=null;await buildBrief()});
async function buildBrief(){const btn=$('.build-brief');btn.disabled=true;btn.querySelector('span').textContent='BUILDING MOVE BRIEF…';
 try{const [from,to]=await Promise.all([resolveInput('from'),resolveInput('to')]);state.from=from;state.to=to;updateResolvedLabels();const [fw,tw,route]=await Promise.all([fetchWeather(from),fetchWeather(to),fetchRoute(from,to)]);state.fromWeather=fw;state.toWeather=tw;state.route=route;renderCore();$('#brief').classList.remove('hidden');setTimeout(()=>{$('#compare').scrollIntoView({behavior:'smooth',block:'start'});renderMap()},80);calcBudget();renderPlan();loadClimate();}catch(err){toast(err.message||'Could not build move brief')}finally{btn.disabled=false;btn.querySelector('span').textContent='BUILD MY MOVE BRIEF'}}
function updateResolvedLabels(){[['from','fromResolved'],['to','toResolved']].forEach(([s,id])=>{const x=state[s];$('#'+id).textContent=x?`${Number(x.latitude).toFixed(3)}, ${Number(x.longitude).toFixed(3)} · ${x.timezone||'timezone —'}`:'Search a city or ZIP code'})}

/* live weather */
async function fetchWeather(x){const u=new URL('https://api.open-meteo.com/v1/forecast');u.searchParams.set('latitude',x.latitude);u.searchParams.set('longitude',x.longitude);u.searchParams.set('current','temperature_2m,apparent_temperature,precipitation,weather_code,wind_speed_10m');u.searchParams.set('daily','weather_code,temperature_2m_max,temperature_2m_min,precipitation_sum,sunrise,sunset');u.searchParams.set('temperature_unit','fahrenheit');u.searchParams.set('wind_speed_unit','mph');u.searchParams.set('precipitation_unit','inch');u.searchParams.set('timezone','auto');u.searchParams.set('forecast_days','7');const r=await fetch(u);if(!r.ok)throw new Error('Weather service unavailable');return r.json()}
const WX={0:'Clear',1:'Mostly clear',2:'Partly cloudy',3:'Overcast',45:'Fog',48:'Rime fog',51:'Light drizzle',53:'Drizzle',55:'Heavy drizzle',61:'Light rain',63:'Rain',65:'Heavy rain',66:'Freezing rain',67:'Heavy freezing rain',71:'Light snow',73:'Snow',75:'Heavy snow',77:'Snow grains',80:'Rain showers',81:'Rain showers',82:'Heavy showers',85:'Snow showers',86:'Heavy snow showers',95:'Thunderstorms',96:'Thunderstorm / hail',99:'Severe thunderstorm / hail'};
const wxText=c=>WX[c]||'Weather'; const isWet=c=>[51,53,55,61,63,65,66,67,71,73,75,77,80,81,82,85,86,95,96,99].includes(+c);

/* routing */
async function fetchRoute(a,b){const air=haversine(a.latitude,a.longitude,b.latitude,b.longitude);try{const u=`https://router.project-osrm.org/route/v1/driving/${a.longitude},${a.latitude};${b.longitude},${b.latitude}?overview=full&geometries=geojson&steps=false`;const r=await fetch(u);if(!r.ok)throw new Error();const j=await r.json();if(j.code!=='Ok'||!j.routes?.[0])throw new Error();const route=j.routes[0];return{type:'road',miles:route.distance/1609.344,hours:route.duration/3600,geometry:route.geometry,air}}catch(e){return{type:'air',miles:air,hours:null,geometry:null,air}}}
function haversine(lat1,lon1,lat2,lon2){const R=3958.7613,d2r=Math.PI/180,dLat=(lat2-lat1)*d2r,dLon=(lon2-lon1)*d2r,a=Math.sin(dLat/2)**2+Math.cos(lat1*d2r)*Math.cos(lat2*d2r)*Math.sin(dLon/2)**2;return 2*R*Math.atan2(Math.sqrt(a),Math.sqrt(1-a))}
function routeTime(h){if(!Number.isFinite(h))return'ROUTE UNAVAILABLE';const hr=Math.floor(h),m=Math.round((h-hr)*60);return`${hr} HR ${m} MIN`}

function renderCore(){const a=state.from,b=state.to,aw=state.fromWeather,bw=state.toWeather,r=state.route;
 $('#fromName').textContent=a.name;$('#toName').textContent=b.name;$('#fromMeta').textContent=[a.admin1,a.country,a.timezone].filter(Boolean).join(' · ');$('#toMeta').textContent=[b.admin1,b.country,b.timezone].filter(Boolean).join(' · ');
 $('#fromTemp').textContent=`${Math.round(aw.current.temperature_2m)}°`;$('#toTemp').textContent=`${Math.round(bw.current.temperature_2m)}°`;$('#fromCondition').textContent=wxText(aw.current.weather_code);$('#toCondition').textContent=wxText(bw.current.weather_code);
 $('#moveMiles').textContent=`${fmt.format(r.miles)} MI`;$('#moveTime').textContent=r.type==='road'?routeTime(r.hours):'STRAIGHT-LINE FALLBACK';$('#routeDistance').textContent=`${fmt.format(r.miles)} miles`;$('#routeDuration').textContent=r.type==='road'?routeTime(r.hours):'Road route unavailable';$('#airDistance').textContent=`${fmt.format(r.air)} MI`;
 $('#mapRouteLabel').textContent=`${a.name.toUpperCase()} → ${b.name.toUpperCase()}`;const tz=((bw.utc_offset_seconds||0)-(aw.utc_offset_seconds||0))/3600;$('#timezoneShift').textContent=tz===0?'NO CHANGE':`${tz>0?'+':''}${tz} HR`;const elev=(+b.elevation||0)-(+a.elevation||0);$('#elevationShift').textContent=`${elev>=0?'+':''}${fmt.format(elev)} M`;
 renderForecast('from',a,aw);renderForecast('to',b,bw);
}
function renderForecast(side,loc,w){$('#'+side+'ForecastName').textContent=loc.name.toUpperCase();const highs=w.daily.temperature_2m_max||[], lows=w.daily.temperature_2m_min||[], rain=w.daily.precipitation_sum||[], codes=w.daily.weather_code||[], dates=w.daily.time||[];const avg=highs.length?highs.reduce((s,n)=>s+n,0)/highs.length:0,wet=rain.reduce((s,n)=>s+(n||0),0);$('#'+side+'WeatherSummary').textContent=`AVG HIGH ${Math.round(avg)}° · ${wet.toFixed(2)} IN PRECIP`;
 $('#'+side+'Forecast').innerHTML=dates.map((d,i)=>{const dt=new Date(d+'T12:00:00');return`<div class="forecast-day"><span>${dt.toLocaleDateString('en-US',{weekday:'short'}).toUpperCase()}</span><i class="${isWet(codes[i])?'rain':''}" title="${esc(wxText(codes[i]))}"></i><b>${Math.round(highs[i])}° / ${Math.round(lows[i])}°</b><small>${esc(wxText(codes[i]))}<br>${(rain[i]||0).toFixed(2)} IN</small></div>`}).join('')}

/* map */
function renderMap(){if(!window.L||!state.from||!state.to)return;const a=state.from,b=state.to;if(!state.map){state.map=L.map('map',{zoomControl:true,attributionControl:true});L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'}).addTo(state.map)}state.layers.forEach(l=>state.map.removeLayer(l));state.layers=[];
 const icon=side=>L.divIcon({className:'',html:`<div class="move-marker ${side}"></div>`,iconSize:[22,22],iconAnchor:[11,11]});const ma=L.marker([a.latitude,a.longitude],{icon:icon('from')}).bindTooltip(`FROM · ${a.name}`),mb=L.marker([b.latitude,b.longitude],{icon:icon('to')}).bindTooltip(`TO · ${b.name}`);ma.addTo(state.map);mb.addTo(state.map);state.layers.push(ma,mb);let line;
 if(state.route.geometry?.coordinates){const pts=state.route.geometry.coordinates.map(([lon,lat])=>[lat,lon]);line=L.polyline(pts,{color:'#16181d',weight:4,opacity:.82});}else line=L.polyline([[a.latitude,a.longitude],[b.latitude,b.longitude]],{color:'#16181d',weight:3,dashArray:'8 8',opacity:.75});line.addTo(state.map);state.layers.push(line);state.map.fitBounds(line.getBounds().pad(.12));setTimeout(()=>state.map.invalidateSize(),120)}

/* climate */
async function loadClimate(){state.climate={from:null,to:null};$('#climateLoading').classList.remove('done');$('#climateLoading').textContent='Building 36 months of climate context…';const year=new Date().getFullYear(),start=`${year-3}-01-01`,end=`${year-1}-12-31`;
 try{const [a,b]=await Promise.all([fetchArchive(state.from,start,end),fetchArchive(state.to,start,end)]);state.climate.from=aggregateClimate(a);state.climate.to=aggregateClimate(b);renderClimate()}catch(e){$('#climateLoading').textContent='Climate archive could not be loaded. Live weather and route data are still available.'}}
async function fetchArchive(x,start,end){const u=new URL('https://archive-api.open-meteo.com/v1/archive');u.searchParams.set('latitude',x.latitude);u.searchParams.set('longitude',x.longitude);u.searchParams.set('start_date',start);u.searchParams.set('end_date',end);u.searchParams.set('daily','temperature_2m_max,temperature_2m_min,precipitation_sum');u.searchParams.set('temperature_unit','fahrenheit');u.searchParams.set('precipitation_unit','inch');u.searchParams.set('timezone','auto');const r=await fetch(u);if(!r.ok)throw new Error('Archive unavailable');return r.json()}
function aggregateClimate(j){const out=Array.from({length:12},()=>({hi:0,lo:0,p:0,n:0})),d=j.daily||{};(d.time||[]).forEach((date,i)=>{const m=+date.slice(5,7)-1,x=out[m];if(Number.isFinite(d.temperature_2m_max?.[i])&&Number.isFinite(d.temperature_2m_min?.[i])){x.hi+=d.temperature_2m_max[i];x.lo+=d.temperature_2m_min[i];x.n++}x.p+=+d.precipitation_sum?.[i]||0});out.forEach(x=>{x.hi=x.n?x.hi/x.n:0;x.lo=x.n?x.lo/x.n:0;x.p=x.p/3});return out}
const MONTHS=['JAN','FEB','MAR','APR','MAY','JUN','JUL','AUG','SEP','OCT','NOV','DEC'];
function renderClimate(){const A=state.climate.from,B=state.climate.to;if(!A||!B)return;$('#monthAxis').innerHTML=MONTHS.map(m=>`<span>${m}</span>`).join('');renderClimateSide('fromClimate','from',state.from,A);renderClimateSide('toClimate','to',state.to,B);$('#climateLoading').classList.add('done');const avg=x=>x.reduce((s,m)=>s+(m.hi+m.lo)/2,0)/12,prec=x=>x.reduce((s,m)=>s+m.p,0),tempDiff=avg(B)-avg(A),precDiff=prec(B)-prec(A);let maxI=0,maxD=-1;A.forEach((m,i)=>{const d=Math.abs(B[i].hi-m.hi);if(d>maxD){maxD=d;maxI=i}});$('#climateTakeaways').innerHTML=`<article class="takeaway"><span>AVERAGE TEMPERATURE SHIFT</span><b>${tempDiff>=0?'+':''}${tempDiff.toFixed(1)}°F</b><p>${tempDiff>3?'Expect a noticeably warmer destination climate.':tempDiff<-3?'Expect a noticeably cooler destination climate.':'Overall temperatures are fairly similar.'}</p></article><article class="takeaway"><span>ANNUAL PRECIPITATION SHIFT</span><b>${precDiff>=0?'+':''}${precDiff.toFixed(1)} IN</b><p>${precDiff>5?'The destination has been materially wetter in the recent archive.':precDiff<-5?'The destination has been materially drier in the recent archive.':'Recent annual precipitation is relatively close.'}</p></article><article class="takeaway"><span>BIGGEST HIGH-TEMP CHANGE</span><b>${MONTHS[maxI]} · ${B[maxI].hi-A[maxI].hi>=0?'+':''}${(B[maxI].hi-A[maxI].hi).toFixed(0)}°</b><p>This is the month where recent average daily highs diverge the most.</p></article>`;renderPlan()}
function renderClimateSide(id,side,loc,data){const avgHi=data.reduce((s,x)=>s+x.hi,0)/12,avgLo=data.reduce((s,x)=>s+x.lo,0)/12,prec=data.reduce((s,x)=>s+x.p,0);$('#'+id).className=`climate-side ${side}`;$('#'+id).innerHTML=`<div class="climate-title"><h3>${esc(loc.name)}</h3><span>3-YEAR RECENT BASELINE</span></div>`+data.map((x,i)=>{const left=Math.max(0,Math.min(100,(x.lo+10)/120*100)),right=Math.max(left+3,Math.min(100,(x.hi+10)/120*100));return`<div class="climate-month"><span>${MONTHS[i]}</span><div class="temp-track"><i class="temp-range" style="left:${left}%;width:${right-left}%"></i></div><b>${Math.round(x.lo)}° / ${Math.round(x.hi)}°</b></div>`}).join('')+`<div class="climate-summary"><div><span>AVG HIGH</span><b>${Math.round(avgHi)}°</b></div><div><span>AVG LOW</span><b>${Math.round(avgLo)}°</b></div><div><span>PRECIP / YR</span><b>${prec.toFixed(1)}″</b></div></div>`}

/* budget */
['currentHousing','newHousing','movingQuote','moveMpg','moveGas','hotelNights','hotelRate','otherCost'].forEach(id=>$('#'+id).addEventListener('input',calcBudget));
function n(id){return +$('#'+id).value||0}function calcBudget(){const miles=state.route?.miles||0, fuel=n('moveMpg')?miles/n('moveMpg')*n('moveGas'):0,truck=n('movingQuote'),hotel=n('hotelNights')*n('hotelRate'),other=n('otherCost'),one=truck+fuel+hotel+other,monthly=n('newHousing')-n('currentHousing'),annual=monthly*12;$('#oneTimeCost').textContent=money(one);$('#fuelMoveCost').textContent=`Includes ${money(fuel)} estimated driving fuel`;$('#annualHousingDelta').textContent=`${annual>=0?'+':''}${money(annual)}`;$('#monthlyHousingDelta').textContent=`${monthly>=0?'+':''}${money(monthly)} / month`;const mx=Math.max(truck,fuel,hotel,other,1);[['barTruck',truck],['barFuel',fuel],['barHotel',hotel],['barOther',other]].forEach(([id,x])=>$('#'+id).style.transform=`scaleX(${Math.max(.02,x/mx)})`)}

/* action plan */
['hasVehicle','hasPets','hasKids','isRenter','remoteWork'].forEach(id=>$('#'+id).addEventListener('change',renderPlan));
const PLAN_KEY='movedesk.plan.v1';function planDone(){try{return JSON.parse(localStorage.getItem(PLAN_KEY)||'{}')}catch(e){return{}}}function setDone(k,v){const x=planDone();x[k]=v;localStorage.setItem(PLAN_KEY,JSON.stringify(x))}
function routeKey(){return state.from&&state.to?`${state.from.name}-${state.from.admin1}|${state.to.name}-${state.to.admin1}`:'route'}
function task(id,title,copy){return{id,title,copy}}
function renderPlan(){if(!state.from||!state.to)return;const differentState=(state.from.country_code==='US'&&state.to.country_code==='US'&&state.from.admin1&&state.to.admin1&&state.from.admin1!==state.to.admin1),long=(state.route?.miles||0)>500,vehicle=$('#hasVehicle').checked,pets=$('#hasPets').checked,kids=$('#hasKids').checked,renter=$('#isRenter').checked,remote=$('#remoteWork').checked;const tempShift=state.climate.from&&state.climate.to?state.climate.to.reduce((s,x)=>s+x.hi,0)/12-state.climate.from.reduce((s,x)=>s+x.hi,0)/12:0;
 const before=[task('notice','Lock the move date','Choose the date, then work backward from leases, work, utilities and movers.'),renter&&task('lease','Handle the current lease','Confirm notice requirements, move-out inspection and deposit process.'),task('usps','Schedule address changes','Create a list for USPS, banks, insurance, subscriptions, employers and important accounts.'),task('utilities','Stage utility shutoff + startup','Overlap critical utilities so the old place is not dark before you leave and the new place is live when you arrive.'),vehicle&&task('vehicleprep','Prep the vehicle','Check tires, fluids, roadside kit and service needs before the drive.'),long&&task('routeprep','Break up the long route','Plan fuel, rest and overnight stops before moving day.'),pets&&task('petrecords','Collect pet records','Keep vaccination, medication and veterinarian records accessible during the move.'),kids&&task('schoolrecords','Request school records','Collect enrollment, immunization and academic documents before leaving.')].filter(Boolean);
 const arrival=[task('keys','Document the new place','Photograph condition, meters and anything that should be documented immediately.'),task('utilities2','Confirm utilities + internet','Test power, water, heating/cooling and connectivity before unpacking around a problem.'),vehicle&&differentState&&task('insurance','Update vehicle insurance location','Tell the insurer the garaging address changed and confirm coverage requirements.'),remote&&task('worktest','Test the work setup','Verify internet speed, backup connectivity and workspace before the first remote workday.'),Math.abs(tempShift)>8&&task('climategear','Adjust for the climate shift',`Recent archive data shows a meaningful temperature change. Check HVAC, clothing, vehicle and home-prep needs for the new pattern.`),pets&&task('petsetup','Settle pet essentials first','Food, medications, containment and a nearby veterinarian should be easy to reach on day one.')].filter(Boolean);
 const month=[differentState&&task('license','Transfer driver license / ID','Check the destination state deadline and required proof documents.'),vehicle&&differentState&&task('registration','Transfer vehicle registration','Check title, inspection, tax and registration requirements in the new state.'),kids&&task('enroll','Complete school enrollment','Confirm district, transportation, calendars and any missing records.'),task('localservices','Build the local short list','Primary care, pharmacy, grocery, repair services and emergency resources.'),task('budgetcheck','Recheck the real monthly cost','After the first bills arrive, replace your planning assumptions with actual housing, utilities and transportation costs.'),task('records','Finish address cleanup','Catch any accounts, licenses or subscriptions that still point to the old address.')].filter(Boolean);
 renderList('beforeList',before);renderList('arrivalList',arrival);renderList('monthList',month);renderOfficialLinks(differentState)}
function renderList(id,items){const done=planDone(),rk=routeKey();$('#'+id).innerHTML=items.map(x=>{const key=`${rk}:${x.id}`,on=!!done[key];return`<label class="check-item ${on?'done':''}" data-key="${esc(key)}"><input type="checkbox" ${on?'checked':''}><div><b>${esc(x.title)}</b><p>${esc(x.copy)}</p></div></label>`}).join('');$$('#'+id+' .check-item').forEach(l=>l.addEventListener('change',()=>{l.classList.toggle('done',l.querySelector('input').checked);setDone(l.dataset.key,l.querySelector('input').checked)}))}
const STATE_PORTALS={'Alabama':'https://www.alabama.gov','Alaska':'https://www.alaska.gov','Arizona':'https://az.gov','Arkansas':'https://portal.arkansas.gov','California':'https://www.ca.gov','Colorado':'https://co.colorado.gov','Connecticut':'https://portal.ct.gov','Delaware':'https://delaware.gov','District of Columbia':'https://dc.gov','Florida':'https://www.myflorida.com','Georgia':'https://georgia.gov','Hawaii':'https://portal.ehawaii.gov','Idaho':'https://www.idaho.gov','Illinois':'https://www.illinois.gov','Indiana':'https://www.in.gov','Iowa':'https://www.iowa.gov','Kansas':'https://portal.kansas.gov','Kentucky':'https://www.kentucky.gov','Louisiana':'https://www.louisiana.gov','Maine':'https://www.maine.gov','Maryland':'https://www.maryland.gov','Massachusetts':'https://www.mass.gov','Michigan':'https://www.michigan.gov','Minnesota':'https://mn.gov','Mississippi':'https://www.ms.gov','Missouri':'https://www.mo.gov','Montana':'https://mt.gov','Nebraska':'https://www.nebraska.gov','Nevada':'https://nv.gov','New Hampshire':'https://www.nh.gov','New Jersey':'https://www.nj.gov','New Mexico':'https://www.nm.gov','New York':'https://www.ny.gov','North Carolina':'https://www.nc.gov','North Dakota':'https://www.nd.gov','Ohio':'https://ohio.gov','Oklahoma':'https://oklahoma.gov','Oregon':'https://www.oregon.gov','Pennsylvania':'https://www.pa.gov','Rhode Island':'https://www.ri.gov','South Carolina':'https://sc.gov','South Dakota':'https://sd.gov','Tennessee':'https://www.tn.gov','Texas':'https://www.texas.gov','Utah':'https://www.utah.gov','Vermont':'https://www.vermont.gov','Virginia':'https://www.virginia.gov','Washington':'https://wa.gov','West Virginia':'https://www.wv.gov','Wisconsin':'https://www.wisconsin.gov','Wyoming':'https://www.wyo.gov'};
function renderOfficialLinks(differentState){const to=state.to,links=[['USPS change of address','https://moversguide.usps.com/'],['USA.gov moving guide','https://www.usa.gov/moving']];if(to.country_code==='US'&&to.admin1&&STATE_PORTALS[to.admin1])links.unshift([`${to.admin1} official portal`,STATE_PORTALS[to.admin1]]);if(differentState)links.push(['State motor vehicle services','https://www.usa.gov/state-motor-vehicle-services']);$('#officialLinks').innerHTML=links.map(([t,u])=>`<a href="${u}" target="_blank" rel="noopener">${esc(t)} ↗</a>`).join('')}
})();
